name: Daily Sync

on:
  schedule:
    # Run daily
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.x'

      - name: Check Go version
        run: go version

      - name: Run sync script
        run: ./tools/sync.sh

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto commit: Daily sync"
          git push
